version: '3.7'
services:
  dalai:
    build: .
    #ports:
    #  - 127.0.0.1:3000:3000
    volumes:
      - ./models/alpaca:/root/dalai/alpaca
      - ./models/llama:/root/dalai/llama
    networks:
      dalai-net:
          aliases:
            - dalai-server
networks:
  dalai-net:
    name: dalai-net